---
kind: pipeline
type: docker
name: netcore

environment:
 srcDir: "src"
 projectName: "FluiTec.AppFx.Console"
 testfilter: "FullyQualifiedName~FluiTec.AppFx.Console&FullyQualifiedName~.Tests"
 integrationfilter: "FullyQualifiedName~FluiTec.AppFx.Console&FullyQualifiedName~.IntegrationTests"
 GIT_SUBMODULE_STRATEGY: recursive

steps:
- name: init
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd $srcDir
  - dotnet restore --verbosity minimal

- name: build
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet build --no-restore